name: Hello World
author: Tom Renner
description: Says hi
inputs:
  who-to-greet:
    description: "Who to say hi to"
    required: true
    default: Tom
outputs:
  time:
    description: "When you're saying hi"
runs:
  using: "docker"
  image: "Dockerfile"
  # env:
  #   THING: "something"
  # entrypoint: sth
  # Passed to Dockerfile as though it is a CMD directive
  args:
    - ${{ inputs.who-to-greet }}
