name: Open GitHub issue
author: Tom Renner
description: "Opens a GitHub issue"
inputs:
  token:
    description: "Github Token"
    required: true
  title:
    description: "Issue title"
    required: true
  body:
    description: "Issue body"
  assignees:
    description: "Issue assignees"
outputs:
  issue:
    description: "The issue object as a json string"
runs:
  using: "node12"
  main: "dist/index.js"