name: CI
on:
  pull_request:
    branches: [develop, master]   # Triggers on a PR _to_ develop or master
  push:
    branches: [develop, master]   # Triggers on push to develop or master, ie. when a PR is merged in


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # Search for any older cache that starts with the same path, so we can restore partial
          # caches, when only part of our dependencies have updated
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: cd my-app && npm ci   # npm install, but "more suitable" for CI environments
      - run: cd my-app && npm run format:check    # Need to `cd` in each command - pwd not persisted
      - run: cd my-app && npm test -- --coverage
        env:
          CI: true
      - name: Upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: my-app/coverage
      - name: Build project
        if: github.event_name == 'push'
        run: cd my-app && npm run build
      - name: Upload build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: my-app/build
      - name: Zip assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cd my-app
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Create a release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: cd my-app && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: cd my-app && npx surge --project ./build  --domain habitual-celery.surge.sh  # Deploys to Surge
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: cd my-app && npx surge --project ./build  --domain upset-reaction.surge.sh  # Deploys to Surge
