name: CI
on:
  pull_request:
    branches: [develop]   # Triggers on a PR _to_ develop
  push:
    branches: [develop]   # Triggers on push to develop, ie. when a PR is merged in


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          # Search for any older cache that starts with the same path, so we can restore partial
          # caches, when only part of our dependencies have updated
          restore-key: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: cd my-app && npm ci   # npm install, but "more suitable" for CI environments
      - run: cd my-app && npm run format:check    # Need to `cd` in each command - pwd not persisted
      - run: cd my-app && npm test -- --coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: cd my-app && npm run build
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: cd my-app && npx surge --project ./build  --domain http://habitual-celery.surge.sh/  # Deploys to Surge
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
