name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # Any steps in this job will run in this container, not directly on the runner
    container: node:13.5.0-alpine3.10
    steps:
      - name: Log container details
        run: |
          node -v
          cat /etc/os-release
