on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Need to have access to the code to run private actions
      - uses: ./.github/actions/create-issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: "Something goes here"
          assignees: |
            tr325
      - run: |
          echo "Issue: ${{ steps.issue.outputs.issue }}"
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
